input {
  kafka {
    bootstrap_servers => "kafka:29092"
    topics_pattern => "outbox\.event.*"
    group_id => "logstash-group"
    codec => json
    auto_offset_reset => "earliest"

    decorate_events => false
  }
}

filter {
  # Parse the JSON string inside "payload"
  json {
    source => "payload"
  }

  # Lowercase index name for Elasticsearch
  mutate {
    lowercase => ["AggregateType"]
  }

  # Remove noisy fields
  mutate {
    remove_field => [
      "payload",
      "schema",
      "event",
      "@version",
      "@timestamp"
    ]
  }
}


output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "%{AggregateType}"
    document_id => "%{AggregateId}"
    action => "%{Operation}"
  }

  stdout { codec => rubydebug }
}